# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# ExportedModelScript.py
# Created on: 2023-04-10 01:02:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
A_point__2_ = "A_point"
A_point = "A_point"
A_Buffer_Model_shp = "D:\\Docs\\GIS\\Lab4\\Layers\\A_Buffer_Model.shp"
E_polyline = "E_polyline"
E_Buffer_Model_shp = "D:\\Docs\\GIS\\Lab4\\Layers\\E_Buffer_Model.shp"
A_E_Buffer_Union_Model_shp = "D:\\Docs\\GIS\\Lab4\\Layers\\A_E_Buffer_Union_Model.shp"
D_polyline = "D_polyline"
D_Buffer_Model_shp = "D:\\Docs\\GIS\\Lab4\\Layers\\D_Buffer_Model.shp"
AE_Sub_D_Model_shp = "D:\\Docs\\GIS\\Lab4\\Layers\\AE_Sub_D_Model.shp"

# Process: Buffer
arcpy.Buffer_analysis(A_point, A_Buffer_Model_shp, "200 Meters", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Buffer (2)
arcpy.Buffer_analysis(E_polyline, E_Buffer_Model_shp, "200 Meters", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Union
arcpy.Union_analysis("D:\\Docs\\GIS\\Lab4\\Layers\\A_Buffer_Model.shp #;D:\\Docs\\GIS\\Lab4\\Layers\\E_Buffer_Model.shp #", A_E_Buffer_Union_Model_shp, "ALL", "", "GAPS")

# Process: Buffer (3)
arcpy.Buffer_analysis(D_polyline, D_Buffer_Model_shp, "200 Meters", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Erase
arcpy.Erase_analysis(A_E_Buffer_Union_Model_shp, D_Buffer_Model_shp, AE_Sub_D_Model_shp, "")

