[package]
name = "Lab2"
version = "1.0.0"
authors = ["Alex Kovalov"]
edition = "2021"
rust-version = "1.81"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["default", "derive"] }
thiserror = "1.0.64"
